apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: ms-kill-sqlservr-process
  namespace: chaos-mesh
spec:
  action: container-kill
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "sqlserver-ag-cluster"
      "kubedb.com/role": "primary"
  containerNames:
    - mssql
  duration: "60s"