apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mssql-replication-latency
  namespace: chaos-mesh
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "sqlserver-ag-cluster"
      "kubedb.com/role": "primary"
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
        "app.kubernetes.io/instance": "sqlserver-ag-cluster"
        "kubedb.com/role": "secondary"
  delay:
    latency: "1s"
    jitter: "50ms"
  duration: "10m"
  direction: both
